// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/havilcorp/yandex-go-musthave-metrics-tpl/domain"

	mock "github.com/stretchr/testify/mock"
)

// IMetric is an autogenerated mock type for the IMetric type
type IMetric struct {
	mock.Mock
}

// AddCounter provides a mock function with given fields: ctx, key, counter
func (_m *IMetric) AddCounter(ctx context.Context, key string, counter int64) error {
	ret := _m.Called(ctx, key, counter)

	if len(ret) == 0 {
		panic("no return value specified for AddCounter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, key, counter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddCounterBulk provides a mock function with given fields: ctx, list
func (_m *IMetric) AddCounterBulk(ctx context.Context, list []domain.Counter) error {
	ret := _m.Called(ctx, list)

	if len(ret) == 0 {
		panic("no return value specified for AddCounterBulk")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.Counter) error); ok {
		r0 = rf(ctx, list)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddGauge provides a mock function with given fields: ctx, key, gauge
func (_m *IMetric) AddGauge(ctx context.Context, key string, gauge float64) error {
	ret := _m.Called(ctx, key, gauge)

	if len(ret) == 0 {
		panic("no return value specified for AddGauge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64) error); ok {
		r0 = rf(ctx, key, gauge)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddGaugeBulk provides a mock function with given fields: ctx, list
func (_m *IMetric) AddGaugeBulk(ctx context.Context, list []domain.Gauge) error {
	ret := _m.Called(ctx, list)

	if len(ret) == 0 {
		panic("no return value specified for AddGaugeBulk")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.Gauge) error); ok {
		r0 = rf(ctx, list)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCounter provides a mock function with given fields: ctx, key
func (_m *IMetric) GetCounter(ctx context.Context, key string) (int64, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetCounter")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGauge provides a mock function with given fields: ctx, key
func (_m *IMetric) GetGauge(ctx context.Context, key string) (float64, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetGauge")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (float64, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIMetric creates a new instance of IMetric. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMetric(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMetric {
	mock := &IMetric{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
