// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeMetricServer is an autogenerated mock type for the UnsafeMetricServer type
type UnsafeMetricServer struct {
	mock.Mock
}

// mustEmbedUnimplementedMetricServer provides a mock function with given fields:
func (_m *UnsafeMetricServer) mustEmbedUnimplementedMetricServer() {
	_m.Called()
}

// NewUnsafeMetricServer creates a new instance of UnsafeMetricServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeMetricServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeMetricServer {
	mock := &UnsafeMetricServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
